### ISSUE TITLE
how to remove extra line under headline?

### ISSUE THREAD

**Issue by mehimme** [krisbalintona/org-hide-drawers#7]
I just updated this package to the newest version (from [995de47ef3652d76d53eed043e50fba9612b77c7](https://github.com/krisbalintona/org-hide-drawers/commit/995de47ef3652d76d53eed043e50fba9612b77c7)), and now I have an extra [Hidden] line under each headline with a drawer, whereas previously the drawer completely disappears and becomes the # after the headline. I tried to remove it by configuring as follows:

`
(setopt org-hide-drawers-display-strings
          (list (list 'property-drawer-regexp "" (rx (0+ anychar)))
                (list 'drawer-regexp "" (rx (0+ anychar)))))
`

but this just made the [Hidden] line become invisible, but still take up space. How to completely remove the extra line? Thanks in advance.

**Comment by krisbalintona** [comment]
Hi, thanks for testing out the new package version.

> I just updated this package to the newest version (from [995de47ef3652d76d53eed043e50fba9612b77c7](https://github.com/krisbalintona/org-hide-drawers/commit/995de47ef3652d76d53eed043e50fba9612b77c7)), and now I have an extra [Hidden] line under each headline with a drawer, whereas previously the drawer completely disappears and becomes the # after the headline.

I think your initial observation of a new "[Hidden]" line under headlines is actually a change that was implemented with the new package version: users can customize how regular drawers (not just property drawers) are displayed. I set the default value for that user option to use have "[Hidden]" be displayed for regular drawers. The extra "[Hidden]" is probably just the :LOGBOOK: drawers under your property drawers.

> I tried to remove it by configuring as follows:
> 
> `(setopt org-hide-drawers-display-strings (list (list 'property-drawer-regexp "" (rx (0+ anychar))) (list 'drawer-regexp "" (rx (0+ anychar)))))`
> 
> but this just made the [Hidden] line become invisible, but still take up space. How to completely remove the extra line? Thanks in advance.

Ah, I see. The behavior you're seeing now is as expected. But you're expect that making a drawer invisible should also "remove" the entire line it's on, correct? To do this, I'll need to make some (hopefully simple) commit(s). When I get to it, I'll ping you here and ask you to test out the new change.

**Comment by mehimme** [comment]
Hey thanks for the fast response, yes I prefer making drawers completely disappear when I didn't need them, to save screen real estate.
Actually in your [screenshot](https://github.com/krisbalintona/org-hide-drawers/blob/main/screenshots/screenshot_1.png), headline 2 shows that behavior.
I'll revert back to the older commit for now, but I'll be happy to test it out, I do have a bunch of different drawer types so being able to configure them separately is nice.

**Comment by krisbalintona** [comment]
Hi @mehimme,

I pushed a change over on the devel branch. Do you mind testing it out for a few days to see if it works as you had in mind?

**Comment by mehimme** [comment]
Thanks for the fast fix! I tried it out and it works great if I want everything to disappear, like `(setopt org-hide-drawers-display-strings (list (list 'all "" (rx (0+ anychar)))))`. But if I want to indicate the presence of a drawer (e.g. by using " #" instead of ""), that string still jumps to the next line, so I'm still not sure how to fully replicate the behavior I had before (and in the screenshot).

**Comment by jtoloe** [comment]
Handling the empty string as a special case doesn't feel right to me.

I would like to see more flexibility instead. Such as being able to remove the line then replace it with my own propertized string that might or might not include one or several newlines... not sure if that is possible.

Also, it would be great if in the case that a second (or third or whatever) drawer follows one that has already been hidden, those would be hidden as well. My use case is that I have a properties drawer followed by a `:logbook:` drawer and I don't need any extra indication for the logbook drawer when it follows the properties drawer. But in entries with only a logbook drawer I still want the indication.

**Comment by krisbalintona** [comment]
> Handling the empty string as a special case doesn't feel right to me.

Is there a more general case you have in mind?

> I would like to see more flexibility instead. Such as being able to remove the line then replace it with my own propertized string that might or might not include one or several newlines... not sure if that is possible.

Have you taken a look at the most recent versions of the package? If you haven't upgraded, I refactored the code such that `org-hide-drawers-display-strings` is the only entry-point and allows more flexibility and expressivity for users.
 
> Also, it would be great if in the case that a second (or third or whatever) drawer follows one that has already been hidden, those would be hidden as well. My use case is that I have a properties drawer followed by a `:logbook:` drawer and I don't need any extra indication for the logbook drawer when it follows the properties drawer. But in entries with only a logbook drawer I still want the indication.

I believe that could be done already with `org-hide-drawers-display-strings`. You could hide all regular drawers named "logbook". And if you're worried about only hiding them sometimes, I still think you can do so with the `'pred` specification.

**Comment by jtoloe** [comment]
I did try the recent version which is why I came back here to see if someone else had the issue with "extra line under headline". :)

I obviously didn't think long enough about the `'pred` variant. I guess it might be possible to have two such entries for the same drawer, one with an indicator in the display string and one with an empty string and return true only for one of them depending on if it is the first or second drawer. Is that what you had in mind as a possible solution?

As for handling the empty string as in the current devel branch, it looks like a very simple approach and gets the old behavior back. I'm quite happy with it and so I will retract my comment on it not "feeling right".

**Comment by jtoloe** [comment]
This gets me what I want:

```
(defun my/org-preceded-by-drawer-p (drawer)
  "Return non-nil if DRAWER is immediately preceded by another drawer.
DRAWER should be an org-element drawer element."
  (save-excursion
    (let ((drawer-beg (org-element-property :begin drawer)))
      (when (and drawer-beg (> drawer-beg 1))
	(goto-char (1- drawer-beg)) ; Move to position before drawer start
	(skip-chars-backward "\n\t ")	; Skip whitespace backwards
	(and (not (bobp))		; Not at beginning of buffer
	     (re-search-backward org-drawer-regexp
				 (line-beginning-position)
				 t))))))
```

```
(setopt org-hide-drawers-display-strings
	`((top-level-property-drawer (propertize "#" 'face 'shadow))
	  (pred (lambda (drawer)
		  (and
		   (eq 'drawer (org-element-type drawer))
		   (string-match-p "logbook" (org-element-property
					      :drawer-name drawer))
		   (my/org-preceded-by-drawer-p drawer)))
		"")
	  (pred (lambda (drawer)
		  (and
		   (eq 'drawer (org-element-type drawer))
		   (string-match-p "logbook" (org-element-property
					      :drawer-name drawer))
		   (not (my/org-preceded-by-drawer-p drawer))))
		(propertize "#" 'face 'shadow))
	  (property-drawer-regexp (propertize " #" 'face 'shadow) "[^a-z]*")))
```
